import {
  subDays,
  startOfMonth,
  subMonths,
  endOfMonth,
  startOfQuarter,
  subQuarters,
  endOfQuarter,
  startOfYear,
  subYears,
  endOfYear,
} from "date-fns";
import { icons } from "../utils/icons";
import { DateType, ISidebarList, ServiceType } from "./types";

export const sidebarList: ISidebarList[] = [
  {
    name: "Orders",
    icons: icons.orders,
  },
  {
    name: "Subscriptions",
    icons: icons.subscriptions,
  },
  {
    name: "Calendar",
    icons: icons.calendar,
  },
  {
    name: "Waitlist",
    icons: icons.waitlist,
  },
];

export const tableData = [
  {
    id: 1,
    createdOn: "Sat, 06 Jan 2024",
    payer: "John Doe",
    status: "Active",
    email: "john.doe@example.com",
    payerPhone: "+91 123 456 7890",
    service: "Private Language Session",
    scheduled: "Sat, 06 Jan 2024",
    serviceType: "private",
  },
  {
    id: 2,
    createdOn: "Sat, 06 Jan 2024",
    payer: "Jane Smith",
    status: "Lead",
    email: "jane.smith@example.com",
    payerPhone: "+91 234 567 8901",
    service: "Fitness Session",
    scheduled: "Sat, 06 Jan 2024",
    serviceType: "public",
  },
  {
    id: 3,
    createdOn: "Sat, 06 Jan 2024",
    payer: "Bob Johnson",
    status: "Inactive",
    email: "bob.johnson@example.com",
    payerPhone: "+91 345 678 9012",
    service: "Boxing Session",
    scheduled: "Sat, 06 Jan 2024",
    serviceType: "public",
  },
  {
    id: 4,
    createdOn: "Sat, 06 Jan 2024",
    payer: "Alice Brown",
    status: "Lead",
    email: "alice.brown@example.com",
    payerPhone: "+91 456 789 0123",
    service: "Swim beginner for class new Session",
    scheduled: "Sat, 06 Jan 2024",
    serviceType: "public",
  },
  {
    id: 5,
    createdOn: "Sat, 06 Jan 2024",
    payer: "Eve Wilson",
    status: "Active",
    email: "eve.wilson@example.com",
    payerPhone: "+91 567 890 1234",
    service: "Private Language Session",
    scheduled: "Sat, 06 Jan 2024",
    serviceType: "private",
  },
  {
    id: 6,
    createdOn: "Sat, 06 Jan 2024",
    payer: "Charlie Davis",
    status: "Lead",
    email: "charlie.davis@example.com",
    payerPhone: "+91 678 901 2345",
    service: "Fitness Session",
    scheduled: "Sat, 06 Jan 2024",
    serviceType: "public",
  },
  {
    id: 7,
    createdOn: "Sat, 06 Jan 2024",
    payer: "Grace Lee",
    status: "Active",
    email: "grace.lee@example.com",
    payerPhone: "+91 789 012 3456",
    service: "Boxing Session",
    scheduled: "Sat, 06 Jan 2024",
    serviceType: "public",
  },
  {
    id: 8,
    createdOn: "Sat, 06 Jan 2024",
    payer: "Frank White",
    status: "Inactive",
    email: "frank.white@example.com",
    payerPhone: "+91 890 123 4567",
    service: "Swim beginner for class new Session",
    scheduled: "Sat, 06 Jan 2024",
    serviceType: "public",
  },
  {
    id: 9,
    createdOn: "Sat, 06 Jan 2024",
    payer: "Hannah Martinez",
    status: "Lead",
    email: "hannah.martinez@example.com",
    payerPhone: "+91 901 234 5678",
    service: "Private Language Session",
    scheduled: "Sat, 06 Jan 2024",
    serviceType: "private",
  },
  {
    id: 10,
    createdOn: "Sat, 06 Jan 2024",
    payer: "Isaac Rodriguez",
    status: "Active",
    email: "isaac.rodriguez@example.com",
    payerPhone: "+91 012 345 6789",
    service: "Fitness Session",
    scheduled: "Sat, 06 Jan 2024",
    serviceType: "public",
  },
];

export const initialDatesArr: DateType[] = [
  { name: "All", id: "all", selected: true },
  { name: "Custom", id: "custom", selected: false },
  {
    name: "Last 30 days",
    id: "thirtydays",
    selected: false,
    minDate: subDays(new Date(), 30),
    maxDate: new Date(),
  },
  {
    name: "This month",
    id: "month",
    selected: false,
    minDate: startOfMonth(new Date()),
    maxDate: new Date(),
  },
  {
    name: "Last month",
    id: "lastmonth",
    selected: false,
    minDate: startOfMonth(subMonths(new Date(), 1)),
    maxDate: endOfMonth(subMonths(new Date(), 1)),
  },
  {
    name: "This quarter",
    id: "quarter",
    selected: false,
    minDate: startOfQuarter(new Date()),
    maxDate: new Date(),
  },
  {
    name: "2 quarters ago",
    id: "quarterago",
    selected: false,
    minDate: startOfQuarter(subQuarters(new Date(), 2)),
    maxDate: endOfQuarter(subQuarters(new Date(), 2)),
  },
  {
    name: "This Year",
    id: "thisyear",
    selected: false,
    minDate: startOfYear(new Date()),
    maxDate: new Date(),
  },
  {
    name: "Last Year",
    id: "lastyear",
    selected: false,
    minDate: startOfYear(subYears(new Date(), 1)),
    maxDate: endOfYear(subYears(new Date(), 1)),
  },
];

export const initialServiceArr: ServiceType[] = [
  { name: "Class", id: "class", selected: true },
  { name: "Appointment", id: "appointment", selected: false },
  { name: "Facility", id: "facility", selected: false },
  { name: "Class Pack", id: "classpack", selected: false },
  { name: "Class Pack", id: "classpack", selected: false },
  { name: "Membership", id: "membership", selected: false },
  { name: "General items", id: "generalitems", selected: false },
];
export const initialStatusArr: ServiceType[] = [
  { name: "Active", id: "active", selected: true },
  { name: "Inactive", id: "inactive", selected: false },
  { name: "Lead", id: "bs", selected: false },
];

export const coloumns = [
  { name: "Created On", isChecked: true },
  { name: "Payer", isChecked: true },
  { name: "Status", isChecked: true },
  { name: "Email", isChecked: true },
  { name: "Payer Phone", isChecked: true },
  { name: "Service", isChecked: true },
  { name: "Scheduled", isChecked: true },
];
